location = /project-path/index.html {
    root /home/app/<project-name>/ui;
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Pragma "no-cache";
    add_header Expires "0";
}

location = /project-path/version.json {
    root /home/app/<project-name>/ui;
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Pragma "no-cache";
    add_header Expires "0";
}

location ^~ /project-path/assets/ {
    root /home/app/<project-name>/ui;
    expires 1y;
    add_header Cache-Control "public, max-age=31536000, immutable";
    try_files $uri =404;
}

location /project-path/ {
    root /home/app/<project-name>/ui;
    try_files $uri $uri/ /project-path/index.html;
    index index.html index.htm;
}
